package mise

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ExportOptions represents options for the mise export command
type ExportOptions struct {
	Dir     string
	DryRun  bool
	Verbose bool
	Format  string // "toml" or "tool-versions"
}

// InstalledTool represents an installed mise tool
type InstalledTool struct {
	Name    string
	Version string
}

// Export exports the current mise environment to files
func Export(opts ExportOptions) error {
	if opts.Dir == "" {
		opts.Dir = "."
	}

	// Expand ~ to home directory
	if strings.HasPrefix(opts.Dir, "~") {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("failed to get home directory: %w", err)
		}
		opts.Dir = filepath.Join(homeDir, opts.Dir[1:])
	}

	if opts.Format == "" {
		opts.Format = "toml"
	}

	// Get installed tools
	tools, err := GetInstalledTools()
	if err != nil {
		return fmt.Errorf("failed to get installed tools: %w", err)
	}

	if len(tools) == 0 {
		fmt.Println("No tools installed in mise.")
		return nil
	}

	if opts.DryRun {
		fmt.Println("[dry-run] Would create directory:", opts.Dir)
		fmt.Printf("[dry-run] Found %d installed tools:\n", len(tools))
		for _, tool := range tools {
			fmt.Printf("  - %s@%s\n", tool.Name, tool.Version)
		}

		switch opts.Format {
		case "toml":
			fmt.Printf("\n[dry-run] Would create file: %s/.mise.toml\n", opts.Dir)
			fmt.Println("[dry-run] Content preview:")
			content := GenerateTOML(tools)
			for _, line := range strings.Split(content, "\n") {
				fmt.Printf("  %s\n", line)
			}
		case "tool-versions":
			fmt.Printf("\n[dry-run] Would create file: %s/.tool-versions\n", opts.Dir)
			fmt.Println("[dry-run] Content preview:")
			content := GenerateToolVersions(tools)
			for _, line := range strings.Split(content, "\n") {
				fmt.Printf("  %s\n", line)
			}
		default:
			return fmt.Errorf("invalid format: %s (must be toml or tool-versions)", opts.Format)
		}

		return nil
	}

	// Create directory
	if err := os.MkdirAll(opts.Dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", opts.Dir, err)
	}

	// Generate and write file
	var filename, content string
	switch opts.Format {
	case "toml":
		filename = ".mise.toml"
		content = GenerateTOML(tools)
	case "tool-versions":
		filename = ".tool-versions"
		content = GenerateToolVersions(tools)
	default:
		return fmt.Errorf("invalid format: %s (must be toml or tool-versions)", opts.Format)
	}

	filePath := filepath.Join(opts.Dir, filename)
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", filePath, err)
	}

	fmt.Printf("Exported %d tools to %s\n", len(tools), filePath)
	fmt.Println("\nExport completed successfully!")
	return nil
}

// GetInstalledTools returns the list of installed mise tools
func GetInstalledTools() ([]InstalledTool, error) {
	cmd := exec.Command("mise", "ls", "--installed")
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("mise command failed (is mise installed?): %w", err)
	}

	return ParseMiseLsOutput(string(output)), nil
}

// ParseMiseLsOutput parses the output of 'mise ls --installed'
func ParseMiseLsOutput(output string) []InstalledTool {
	var tools []InstalledTool
	seen := make(map[string]bool)

	scanner := bufio.NewScanner(strings.NewReader(output))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		// Parse line: "node  20.10.0  ~/.local/share/mise/installs/node/20.10.0"
		// or: "python 3.12.0 (set by ~/.config/mise/config.toml)"
		fields := strings.Fields(line)
		if len(fields) >= 2 {
			name := fields[0]
			version := fields[1]

			// Skip if already seen (take the first version for each tool)
			key := name + "@" + version
			if seen[key] {
				continue
			}
			seen[key] = true

			tools = append(tools, InstalledTool{
				Name:    name,
				Version: version,
			})
		}
	}

	return tools
}

// GenerateTOML generates .mise.toml content from installed tools
func GenerateTOML(tools []InstalledTool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by goodbye export mise\n")
	sb.WriteString("[tools]\n")

	for _, tool := range tools {
		sb.WriteString(fmt.Sprintf("%s = \"%s\"\n", tool.Name, tool.Version))
	}

	return sb.String()
}

// GenerateToolVersions generates .tool-versions content from installed tools
func GenerateToolVersions(tools []InstalledTool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by goodbye export mise\n")

	for _, tool := range tools {
		sb.WriteString(fmt.Sprintf("%s %s\n", tool.Name, tool.Version))
	}

	return sb.String()
}
