package mise

import (
	"reflect"
	"testing"
)

func TestParseMiseLsOutput(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected []InstalledTool
	}{
		{
			name:     "empty output",
			input:    "",
			expected: nil,
		},
		{
			name: "single tool",
			input: `node  20.10.0  ~/.local/share/mise/installs/node/20.10.0`,
			expected: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
			},
		},
		{
			name: "multiple tools",
			input: `node    20.10.0   ~/.local/share/mise/installs/node/20.10.0
python  3.12.0    ~/.local/share/mise/installs/python/3.12.0
go      1.21.5    ~/.local/share/mise/installs/go/1.21.5`,
			expected: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
				{Name: "python", Version: "3.12.0"},
				{Name: "go", Version: "1.21.5"},
			},
		},
		{
			name: "with set by info",
			input: `node    20.10.0  (set by ~/.config/mise/config.toml)
python  3.12.0   (set by ~/.tool-versions)`,
			expected: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
				{Name: "python", Version: "3.12.0"},
			},
		},
		{
			name: "with empty lines",
			input: `node  20.10.0  ~/.local/share/mise/installs/node/20.10.0

python  3.12.0    ~/.local/share/mise/installs/python/3.12.0
`,
			expected: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
				{Name: "python", Version: "3.12.0"},
			},
		},
		{
			name: "duplicate versions filtered",
			input: `node  20.10.0  ~/.local/share/mise/installs/node/20.10.0
node  20.10.0  (set by ~/.config/mise/config.toml)
python  3.12.0  ~/.local/share/mise/installs/python/3.12.0`,
			expected: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
				{Name: "python", Version: "3.12.0"},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := ParseMiseLsOutput(tt.input)
			if !reflect.DeepEqual(result, tt.expected) {
				t.Errorf("ParseMiseLsOutput() = %v, want %v", result, tt.expected)
			}
		})
	}
}

func TestGenerateTOML(t *testing.T) {
	tests := []struct {
		name     string
		tools    []InstalledTool
		expected string
	}{
		{
			name:  "empty tools",
			tools: []InstalledTool{},
			expected: `# Generated by goodbye export mise
[tools]
`,
		},
		{
			name: "single tool",
			tools: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
			},
			expected: `# Generated by goodbye export mise
[tools]
node = "20.10.0"
`,
		},
		{
			name: "multiple tools",
			tools: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
				{Name: "python", Version: "3.12.0"},
				{Name: "go", Version: "1.21.5"},
			},
			expected: `# Generated by goodbye export mise
[tools]
node = "20.10.0"
python = "3.12.0"
go = "1.21.5"
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateTOML(tt.tools)
			if result != tt.expected {
				t.Errorf("GenerateTOML() = %q, want %q", result, tt.expected)
			}
		})
	}
}

func TestGenerateToolVersions(t *testing.T) {
	tests := []struct {
		name     string
		tools    []InstalledTool
		expected string
	}{
		{
			name:  "empty tools",
			tools: []InstalledTool{},
			expected: `# Generated by goodbye export mise
`,
		},
		{
			name: "single tool",
			tools: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
			},
			expected: `# Generated by goodbye export mise
node 20.10.0
`,
		},
		{
			name: "multiple tools",
			tools: []InstalledTool{
				{Name: "node", Version: "20.10.0"},
				{Name: "python", Version: "3.12.0"},
				{Name: "go", Version: "1.21.5"},
			},
			expected: `# Generated by goodbye export mise
node 20.10.0
python 3.12.0
go 1.21.5
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateToolVersions(tt.tools)
			if result != tt.expected {
				t.Errorf("GenerateToolVersions() = %q, want %q", result, tt.expected)
			}
		})
	}
}
